# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 09:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_geoname', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
            ],
        ),
    ]
